### ISSUE TITLE
Move docs to GitHub wiki

### ISSUE THREAD

**Issue by SuicSoft** [shashlik/docs#2]
Instructions and documents should be moved to a wiki

**Comment by bittner** [comment]
Alternatively, proper documentation written in reStructuredText using [Sphinx](http://www.sphinx-doc.org/en/stable/) could live in a `docs/` folder of the main (source code / binary) repository.

**Comment by davidedmundson** [comment]
This repo is outdated and from a former approach. For new docs see the main shashlik website.

**Comment by bittner** [comment]
@davidedmundson Can you please add this information to the respository header? Including a link to the new repository.

**Comment by SuicSoft** [comment]
@davidedmundson Have you checked my other comments
